export interface ConfigData{

    configurationName: string,
    deviceType: string,
    validFrom: string,
    validTo: string,
    temperatureProb: string,
    batteryStatus: string,
    batteryMinRange: number,
    batteryMaxRange: number,
    humidityStatus: string,
    humidityMinRange: number,
    humidityMaxRange: number,
    lightStatus: string,
    lightMinRange: number,
    lightMaxRange: number,
    shockStatus: string,
    shockRange: number,
    shockDuration: number,
    tiltStatus: string,
    tiltMinRange: number,
    tiltMaxRange: number,
    pressureStatus: string,
    pressureMinRange: number,
    pressureMaxRange: number,
    temperatureStatus: string,
    temperatureMinRange: number,
    temperatureMaxRange: number
}